plugins {
    id 'java'
    id 'application'
}

group = 'com.gustavo'
version = '0.1.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
    implementation 'com.google.code.gson:gson:2.10.1'
}

application {
    mainClass = 'com.gustavo.todo.app.Main'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    useJUnitPlatform()
}

// Permite rodar o projeto com: ./gradlew run
run {
    standardInput = System.in
    enableAssertions = true
}
